/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Source;

import java.awt.Color;
import javax.swing.*;

/**
 *
 * @author shali
 */
public class Welcome extends javax.swing.JFrame {

    /**
     * Creates new form Welcome
     */
    public Welcome() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        pnlMenu = new javax.swing.JPanel();
        lblLogOut = new javax.swing.JLabel();
        lblFullName = new javax.swing.JLabel();
        lblWelcome = new javax.swing.JLabel();
        pnlBadminton = new javax.swing.JPanel();
        lblBadminton = new javax.swing.JLabel();
        pnlCricket = new javax.swing.JPanel();
        lblCricket = new javax.swing.JLabel();
        pnlBasketball = new javax.swing.JPanel();
        lblBasketball = new javax.swing.JLabel();
        pnlFootball = new javax.swing.JPanel();
        lblFootball = new javax.swing.JLabel();
        pnlHokey = new javax.swing.JPanel();
        lblHokey = new javax.swing.JLabel();
        pnlNetball = new javax.swing.JPanel();
        lblNetball = new javax.swing.JLabel();
        pnlRuger = new javax.swing.JPanel();
        lblRuger = new javax.swing.JLabel();
        pnlTabletenis = new javax.swing.JPanel();
        lblTabletenis = new javax.swing.JLabel();
        pnlVollyball = new javax.swing.JPanel();
        lblVollyball = new javax.swing.JLabel();
        pnlContent = new javax.swing.JPanel();
        pnlBadmintonMain = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel13 = new javax.swing.JLabel();
        jSpinner2 = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jLabel14 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList<>();
        jLabel15 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        pnlBasketballMain = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        pnlCricketMain = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        pnlFootballMain = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        pnlHokeyMain = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        pnlNetballMain = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        pnlRugerMain = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        pnlTabletenisMain = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        pnlVollyballMain = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocationByPlatform(true);
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(850, 600));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        pnlMenu.setBackground(new java.awt.Color(54, 33, 89));

        lblLogOut.setForeground(new java.awt.Color(255, 0, 51));
        lblLogOut.setText("Log Out");

        lblFullName.setForeground(new java.awt.Color(255, 255, 255));
        lblFullName.setText("KP Shalinda A Silva");

        lblWelcome.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        lblWelcome.setForeground(new java.awt.Color(255, 255, 255));
        lblWelcome.setText("Welcome");

        pnlBadminton.setBackground(new java.awt.Color(111, 107, 150));
        pnlBadminton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBadmintonMousePressed(evt);
            }
        });
        pnlBadminton.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBadminton.setBackground(new java.awt.Color(111, 107, 150));
        lblBadminton.setForeground(new java.awt.Color(255, 255, 255));
        lblBadminton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBadminton.setText("Badminton");
        pnlBadminton.add(lblBadminton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlCricket.setBackground(new java.awt.Color(54, 33, 89));
        pnlCricket.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlCricketMousePressed(evt);
            }
        });
        pnlCricket.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblCricket.setBackground(new java.awt.Color(111, 107, 150));
        lblCricket.setForeground(new java.awt.Color(255, 255, 255));
        lblCricket.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblCricket.setText("Cricket");
        pnlCricket.add(lblCricket, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlBasketball.setBackground(new java.awt.Color(54, 33, 89));
        pnlBasketball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlBasketballMousePressed(evt);
            }
        });
        pnlBasketball.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblBasketball.setBackground(new java.awt.Color(54, 33, 89));
        lblBasketball.setForeground(new java.awt.Color(255, 255, 255));
        lblBasketball.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblBasketball.setText("Basketball");
        pnlBasketball.add(lblBasketball, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlFootball.setBackground(new java.awt.Color(54, 33, 89));
        pnlFootball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlFootballMousePressed(evt);
            }
        });
        pnlFootball.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblFootball.setBackground(new java.awt.Color(111, 107, 150));
        lblFootball.setForeground(new java.awt.Color(255, 255, 255));
        lblFootball.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblFootball.setText("Football");
        pnlFootball.add(lblFootball, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlHokey.setBackground(new java.awt.Color(54, 33, 89));
        pnlHokey.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlHokeyMousePressed(evt);
            }
        });
        pnlHokey.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblHokey.setBackground(new java.awt.Color(111, 107, 150));
        lblHokey.setForeground(new java.awt.Color(255, 255, 255));
        lblHokey.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblHokey.setText("Hokey");
        pnlHokey.add(lblHokey, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlNetball.setBackground(new java.awt.Color(54, 33, 89));
        pnlNetball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlNetballMousePressed(evt);
            }
        });
        pnlNetball.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNetball.setBackground(new java.awt.Color(111, 107, 150));
        lblNetball.setForeground(new java.awt.Color(255, 255, 255));
        lblNetball.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblNetball.setText("Netball");
        pnlNetball.add(lblNetball, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlRuger.setBackground(new java.awt.Color(54, 33, 89));
        pnlRuger.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlRugerMousePressed(evt);
            }
        });
        pnlRuger.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblRuger.setBackground(new java.awt.Color(111, 107, 150));
        lblRuger.setForeground(new java.awt.Color(255, 255, 255));
        lblRuger.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblRuger.setText("Ruger");
        pnlRuger.add(lblRuger, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlTabletenis.setBackground(new java.awt.Color(54, 33, 89));
        pnlTabletenis.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlTabletenisMousePressed(evt);
            }
        });
        pnlTabletenis.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTabletenis.setBackground(new java.awt.Color(111, 107, 150));
        lblTabletenis.setForeground(new java.awt.Color(255, 255, 255));
        lblTabletenis.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTabletenis.setText("Tabletenis");
        pnlTabletenis.add(lblTabletenis, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        pnlVollyball.setBackground(new java.awt.Color(54, 33, 89));
        pnlVollyball.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mousePressed(java.awt.event.MouseEvent evt) {
                pnlVollyballMousePressed(evt);
            }
        });
        pnlVollyball.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblVollyball.setBackground(new java.awt.Color(111, 107, 150));
        lblVollyball.setForeground(new java.awt.Color(255, 255, 255));
        lblVollyball.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblVollyball.setText("Vollyball");
        pnlVollyball.add(lblVollyball, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 280, 30));

        javax.swing.GroupLayout pnlMenuLayout = new javax.swing.GroupLayout(pnlMenu);
        pnlMenu.setLayout(pnlMenuLayout);
        pnlMenuLayout.setHorizontalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnlTabletenis, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlVollyball, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                    .addGroup(pnlMenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(pnlBadminton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLayout.createSequentialGroup()
                        .addGap(235, 235, 235)
                        .addComponent(lblLogOut))
                    .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblFullName)
                        .addComponent(lblWelcome, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, pnlMenuLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnlRuger, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlNetball, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlHokey, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlFootball, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlBasketball, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnlCricket, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        pnlMenuLayout.setVerticalGroup(
            pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlMenuLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblWelcome)
                .addGap(29, 29, 29)
                .addGroup(pnlMenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblFullName)
                    .addComponent(lblLogOut))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 56, Short.MAX_VALUE)
                .addComponent(pnlBadminton, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlBasketball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlCricket, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlFootball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlHokey, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlNetball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlRuger, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlTabletenis, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnlVollyball, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(128, 128, 128))
        );

        jPanel1.add(pnlMenu, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 290, 600));

        pnlContent.setBackground(new java.awt.Color(255, 255, 255));
        pnlContent.setLayout(new java.awt.CardLayout());

        jPanel2.setBackground(new java.awt.Color(110, 88, 222));

        jLabel1.setBackground(new java.awt.Color(255, 255, 255));
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Home/");

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Badminton");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(37, 37, 37)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel3.setBackground(new java.awt.Color(153, 153, 153));

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Check Availability");

        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Chose Date :");

        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Chose Time :");

        jButton1.setText("Check");

        jLabel14.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(0, 255, 0));
        jLabel14.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel14.setText("Available !");

        jList1.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Court A", "Court B", "Court C" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Court No :");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel15))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jSpinner1)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 100, Short.MAX_VALUE))
                        .addGap(33, 33, 33)
                        .addComponent(jLabel13)
                        .addGap(18, 18, 18)
                        .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(36, 36, 36)
                        .addComponent(jButton1)))
                .addContainerGap(39, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jSpinner2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel14)
                .addContainerGap())
        );

        jPanel4.setBackground(new java.awt.Color(153, 153, 153));

        jLabel16.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Make a Booking");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addComponent(jLabel16)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel16)
                .addContainerGap(300, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnlBadmintonMainLayout = new javax.swing.GroupLayout(pnlBadmintonMain);
        pnlBadmintonMain.setLayout(pnlBadmintonMainLayout);
        pnlBadmintonMainLayout.setHorizontalGroup(
            pnlBadmintonMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(pnlBadmintonMainLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlBadmintonMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        pnlBadmintonMainLayout.setVerticalGroup(
            pnlBadmintonMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBadmintonMainLayout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pnlContent.add(pnlBadmintonMain, "card2");

        jLabel4.setText("Basketball");

        javax.swing.GroupLayout pnlBasketballMainLayout = new javax.swing.GroupLayout(pnlBasketballMain);
        pnlBasketballMain.setLayout(pnlBasketballMainLayout);
        pnlBasketballMainLayout.setHorizontalGroup(
            pnlBasketballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasketballMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel4)
                .addContainerGap(254, Short.MAX_VALUE))
        );
        pnlBasketballMainLayout.setVerticalGroup(
            pnlBasketballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlBasketballMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel4)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlBasketballMain, "card2");

        jLabel5.setText("Cricket");

        javax.swing.GroupLayout pnlCricketMainLayout = new javax.swing.GroupLayout(pnlCricketMain);
        pnlCricketMain.setLayout(pnlCricketMainLayout);
        pnlCricketMainLayout.setHorizontalGroup(
            pnlCricketMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCricketMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel5)
                .addContainerGap(273, Short.MAX_VALUE))
        );
        pnlCricketMainLayout.setVerticalGroup(
            pnlCricketMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlCricketMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel5)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlCricketMain, "card2");

        jLabel6.setText("Football");

        javax.swing.GroupLayout pnlFootballMainLayout = new javax.swing.GroupLayout(pnlFootballMain);
        pnlFootballMain.setLayout(pnlFootballMainLayout);
        pnlFootballMainLayout.setHorizontalGroup(
            pnlFootballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFootballMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel6)
                .addContainerGap(270, Short.MAX_VALUE))
        );
        pnlFootballMainLayout.setVerticalGroup(
            pnlFootballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlFootballMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel6)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlFootballMain, "card2");

        jLabel7.setText("Hokey");

        javax.swing.GroupLayout pnlHokeyMainLayout = new javax.swing.GroupLayout(pnlHokeyMain);
        pnlHokeyMain.setLayout(pnlHokeyMainLayout);
        pnlHokeyMainLayout.setHorizontalGroup(
            pnlHokeyMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHokeyMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel7)
                .addContainerGap(279, Short.MAX_VALUE))
        );
        pnlHokeyMainLayout.setVerticalGroup(
            pnlHokeyMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlHokeyMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel7)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlHokeyMain, "card2");

        jLabel8.setText("Netball");

        javax.swing.GroupLayout pnlNetballMainLayout = new javax.swing.GroupLayout(pnlNetballMain);
        pnlNetballMain.setLayout(pnlNetballMainLayout);
        pnlNetballMainLayout.setHorizontalGroup(
            pnlNetballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNetballMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel8)
                .addContainerGap(275, Short.MAX_VALUE))
        );
        pnlNetballMainLayout.setVerticalGroup(
            pnlNetballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlNetballMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel8)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlNetballMain, "card2");

        jLabel9.setText("Ruger");

        javax.swing.GroupLayout pnlRugerMainLayout = new javax.swing.GroupLayout(pnlRugerMain);
        pnlRugerMain.setLayout(pnlRugerMainLayout);
        pnlRugerMainLayout.setHorizontalGroup(
            pnlRugerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRugerMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel9)
                .addContainerGap(280, Short.MAX_VALUE))
        );
        pnlRugerMainLayout.setVerticalGroup(
            pnlRugerMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlRugerMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel9)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlRugerMain, "card2");

        jLabel10.setText("Tabletenis");

        javax.swing.GroupLayout pnlTabletenisMainLayout = new javax.swing.GroupLayout(pnlTabletenisMain);
        pnlTabletenisMain.setLayout(pnlTabletenisMainLayout);
        pnlTabletenisMainLayout.setHorizontalGroup(
            pnlTabletenisMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabletenisMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel10)
                .addContainerGap(255, Short.MAX_VALUE))
        );
        pnlTabletenisMainLayout.setVerticalGroup(
            pnlTabletenisMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlTabletenisMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel10)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlTabletenisMain, "card2");

        jLabel11.setText("Vollyball");

        javax.swing.GroupLayout pnlVollyballMainLayout = new javax.swing.GroupLayout(pnlVollyballMain);
        pnlVollyballMain.setLayout(pnlVollyballMainLayout);
        pnlVollyballMainLayout.setHorizontalGroup(
            pnlVollyballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVollyballMainLayout.createSequentialGroup()
                .addGap(246, 246, 246)
                .addComponent(jLabel11)
                .addContainerGap(267, Short.MAX_VALUE))
        );
        pnlVollyballMainLayout.setVerticalGroup(
            pnlVollyballMainLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlVollyballMainLayout.createSequentialGroup()
                .addGap(281, 281, 281)
                .addComponent(jLabel11)
                .addContainerGap(303, Short.MAX_VALUE))
        );

        pnlContent.add(pnlVollyballMain, "card2");

        jPanel1.add(pnlContent, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 0, 560, 600));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void pnlBadmintonMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBadmintonMousePressed
        // side menu color change:
        setColorSelect(pnlBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlBadmintonMain);
            pnlContent.repaint();
            pnlContent.revalidate();
            
    }//GEN-LAST:event_pnlBadmintonMousePressed

    private void pnlCricketMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlCricketMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        setColorSelect(pnlCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlCricketMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlCricketMousePressed

    private void pnlBasketballMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlBasketballMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        setColorSelect(pnlBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlBasketballMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlBasketballMousePressed

    private void pnlFootballMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlFootballMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        setColorSelect(pnlFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlFootballMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlFootballMousePressed

    private void pnlHokeyMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlHokeyMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        setColorSelect(pnlHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlHokeyMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlHokeyMousePressed

    private void pnlNetballMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlNetballMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        setColorSelect(pnlNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlNetballMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlNetballMousePressed

    private void pnlRugerMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlRugerMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        setColorSelect(pnlRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlRugerMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlRugerMousePressed

    private void pnlTabletenisMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlTabletenisMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        setColorSelect(pnlTabletenis);
        resetColorSelect(pnlVollyball,lblVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlTabletenisMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlTabletenisMousePressed

    private void pnlVollyballMousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnlVollyballMousePressed
        // side menu color change:
        resetColorSelect(pnlBadminton,lblBadminton);
        resetColorSelect(pnlBasketball,lblBasketball);
        resetColorSelect(pnlCricket,lblCricket);
        resetColorSelect(pnlFootball,lblFootball);
        resetColorSelect(pnlHokey,lblHokey);
        resetColorSelect(pnlNetball,lblNetball);
        resetColorSelect(pnlRuger,lblRuger);
        resetColorSelect(pnlTabletenis,lblTabletenis);
        setColorSelect(pnlVollyball);
        
        //change main panel:
            //removing panel:
            pnlContent.removeAll();
            pnlContent.repaint();
            pnlContent.revalidate();
            
            //adding panel:
            pnlContent.add(pnlVollyballMain);
            pnlContent.repaint();
            pnlContent.revalidate();
    }//GEN-LAST:event_pnlVollyballMousePressed
    
    void setColorSelect(JPanel panel){
        panel.setBackground(new Color(111,107,150));
        
    }
    
        void resetColorSelect(JPanel panel,JLabel label){
        panel.setBackground(new Color(54,33,89));
        label.setForeground(new Color(255,255,255));
        
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Welcome.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Welcome().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JSpinner jSpinner2;
    private javax.swing.JLabel lblBadminton;
    private javax.swing.JLabel lblBasketball;
    private javax.swing.JLabel lblCricket;
    private javax.swing.JLabel lblFootball;
    private javax.swing.JLabel lblFullName;
    private javax.swing.JLabel lblHokey;
    private javax.swing.JLabel lblLogOut;
    private javax.swing.JLabel lblNetball;
    private javax.swing.JLabel lblRuger;
    private javax.swing.JLabel lblTabletenis;
    private javax.swing.JLabel lblVollyball;
    private javax.swing.JLabel lblWelcome;
    private javax.swing.JPanel pnlBadminton;
    private javax.swing.JPanel pnlBadmintonMain;
    private javax.swing.JPanel pnlBasketball;
    private javax.swing.JPanel pnlBasketballMain;
    private javax.swing.JPanel pnlContent;
    private javax.swing.JPanel pnlCricket;
    private javax.swing.JPanel pnlCricketMain;
    private javax.swing.JPanel pnlFootball;
    private javax.swing.JPanel pnlFootballMain;
    private javax.swing.JPanel pnlHokey;
    private javax.swing.JPanel pnlHokeyMain;
    private javax.swing.JPanel pnlMenu;
    private javax.swing.JPanel pnlNetball;
    private javax.swing.JPanel pnlNetballMain;
    private javax.swing.JPanel pnlRuger;
    private javax.swing.JPanel pnlRugerMain;
    private javax.swing.JPanel pnlTabletenis;
    private javax.swing.JPanel pnlTabletenisMain;
    private javax.swing.JPanel pnlVollyball;
    private javax.swing.JPanel pnlVollyballMain;
    // End of variables declaration//GEN-END:variables
}
